# Makefile for fat95 filesystem handler
# Build using vasm (assembler)
#
# Usage: make [options] [target]
#   help - show detailed usage output

# Driver Version (update these for new releases)
VERSION_MAJOR = 3
VERSION_MINOR = 19
VERSION_SUFFIX = -dev
DATE = 25.01.2026

# Versions (update these for new releases)
INSTALL95_VERSION_MAJOR = 3
INSTALL95_VERSION_MINOR = 19
INSTALL95_VERSION_SUFFIX =
INSTALL95_DATE = 25.01.2026

DD_VERSION_MAJOR = 1
DD_VERSION_MINOR = 05
DD_VERSION_SUFFIX =
DD_DATE = 25.01.2026

DEBUG95_VERSION_MAJOR = 3
DEBUG95_VERSION_MINOR = 19
DEBUG95_VERSION_SUFFIX =
DEBUG95_DATE = 25.01.2026

SETFILESIZE_VERSION_MAJOR = 1
SETFILESIZE_VERSION_MINOR = 1
SETFILESIZE_VERSION_SUFFIX =
SETFILESIZE_DATE = 25.01.2026

BOOT95_VERSION_MAJOR = 3
BOOT95_VERSION_MINOR = 19
BOOT95_VERSION_SUFFIX =
BOOT95_DATE = 25.01.2026

# Derived version
VERSION = $(VERSION_MAJOR).$(VERSION_MINOR)$(VERSION_SUFFIX)
VERSION_NODOT = $(VERSION_MAJOR)$(VERSION_MINOR)
VERSION_FILENAME = $(VERSION_MAJOR).$(VERSION_MINOR)$(VERSION_SUFFIX)

INSTALL95_VERSION = $(INSTALL95_VERSION_MAJOR).$(INSTALL95_VERSION_MINOR)$(INSTALL95_VERSION_SUFFIX)
DD_VERSION = $(DD_VERSION_MAJOR).$(DD_VERSION_MINOR)$(DD_VERSION_SUFFIX)
DEBUG95_VERSION = $(DEBUG95_VERSION_MAJOR).$(DEBUG95_VERSION_MINOR)$(DEBUG95_VERSION_SUFFIX)
SETFILESIZE_VERSION = $(SETFILESIZE_VERSION_MAJOR).$(SETFILESIZE_VERSION_MINOR)$(SETFILESIZE_VERSION_SUFFIX)
BOOT95_VERSION = $(BOOT95_VERSION_MAJOR).$(BOOT95_VERSION_MINOR)$(BOOT95_VERSION_SUFFIX)

# Generate version include files for assembler
VERSION_FAT95_INC = src/fat95_version.i
VERSION_INSTALL95_INC = src/install95_version.i
VERSION_DD_INC = src/dd_version.i
VERSION_DEBUG95_INC = src/debug95_version.i
VERSION_SETFILESIZE_INC = src/setfilesize_version.i
VERSION_BOOT95_INC = src/boot95_version.i

# Verbose mode (V=1 for verbose output)
ifeq ($(V),1)
  Q =
  DEFINITIONS =
else
  Q = @
  DEFINITIONS = -quiet
endif

# Tools (override these for different installations)
#VASM_HOME = /opt/vbcc
VASM_HOME = /opt/vasm
VASM = $(VASM_HOME)/bin/vasmm68k_mot

# Flags
VASMFLAGS = -Fhunkexe -m68020 -nosym $(DEFINITIONS)

# Directories
SRCDIR = src
OUTDIR = l

# Files: Driver
SOURCE = $(SRCDIR)/fat95.s
TARGET = $(OUTDIR)/fat95

# Files: Tools
SOURCE_INSTALL95 = $(SRCDIR)/install95.s
TARGET_INSTALL95 = $(OUTDIR)/install95

SOURCE_DD = $(SRCDIR)/dd.s
TARGET_DD = c/dd

SOURCE_DEBUG95 = $(SRCDIR)/debug95.s
TARGET_DEBUG95 = c/debug95

SOURCE_SETFILESIZE = $(SRCDIR)/setfilesize.s
TARGET_SETFILESIZE = c/SetFileSize

SOURCE_BOOT95 = $(SRCDIR)/boot95.s
TARGET_BOOT95 = c/boot95

# Files: Release
RELEASE_NAME = fat95.$(VERSION_FILENAME)
ARCHIVE_NAME = $(RELEASE_NAME).lha
README_NAME = $(RELEASE_NAME).readme
README_TEMPLATE = fat95.readme.in
README_INFO_TEMPLATE = fat95.readme.info.in
LHA = lha

# ============================================================
# Build targets
# ============================================================

# Default target
all: $(TARGET) $(TARGET_INSTALL95) $(TARGET_DD) $(TARGET_DEBUG95) $(TARGET_SETFILESIZE) $(TARGET_BOOT95)

# Generate version include file (always check, only update if changed)
# Uses a stamp file to track the current version string
VERSION_STAMP = .version-stamp
.PHONY: FORCE
FORCE:

$(VERSION_STAMP): FORCE
	$(Q)echo "$(VERSION) $(DATE)" > $(VERSION_STAMP).tmp
	$(Q)if ! cmp -s $(VERSION_STAMP).tmp $(VERSION_STAMP) 2>/dev/null; then \
		mv $(VERSION_STAMP).tmp $(VERSION_STAMP); \
	else \
		rm -f $(VERSION_STAMP).tmp; \
	fi

# Unified version include file generation function
# Usage: $(call gen_version_inc,output_file,tool_name,version_major,version_minor,version_string,macro_name,date)
define gen_version_inc
	$(Q)echo "  VERSION $(2) $(5)" >&2
	$(Q)echo "; Auto-generated by Makefile - do not edit" > $(1)
	$(if $(3),$(Q)echo "FILE_VERSION	= $(3)" >> $(1))
	$(if $(4),$(Q)echo "FILE_REVISION	= $(4)" >> $(1))
	$(Q)echo "$(6)	macro" >> $(1)
	$(Q)echo "	dc.b	\"$(2) $(5) ($(7))\"" >> $(1)
	$(Q)echo "	endm" >> $(1)
endef

# Generate fat95_version.i for fat95 (uses VERSION_STRING macro)
$(VERSION_FAT95_INC): $(VERSION_STAMP)
	$(call gen_version_inc,$@,fat95,$(VERSION_MAJOR),$(VERSION_MINOR),$(VERSION),VERSION_STRING,$(DATE))

# Generate tool-specific version files (all use VER_STRING macro)
$(VERSION_INSTALL95_INC): $(VERSION_STAMP)
	$(call gen_version_inc,$@,install95,$(INSTALL95_VERSION_MAJOR),$(INSTALL95_VERSION_MINOR),$(INSTALL95_VERSION),VER_STRING,$(INSTALL95_DATE))

$(VERSION_DD_INC): $(VERSION_STAMP)
	$(call gen_version_inc,$@,dd,,,$(DD_VERSION),VER_STRING,$(DD_DATE))

$(VERSION_DEBUG95_INC): $(VERSION_STAMP)
	$(call gen_version_inc,$@,debug95,,,$(DEBUG95_VERSION),VER_STRING,$(DEBUG95_DATE))

$(VERSION_SETFILESIZE_INC): $(VERSION_STAMP)
	$(call gen_version_inc,$@,SetFileSize,,,$(SETFILESIZE_VERSION),VER_STRING,$(SETFILESIZE_DATE))

$(VERSION_BOOT95_INC): $(VERSION_STAMP)
	$(call gen_version_inc,$@,boot95,$(BOOT95_VERSION_MAJOR),$(BOOT95_VERSION_MINOR),$(BOOT95_VERSION),VER_STRING,$(BOOT95_DATE))

# Build fat95 handler
$(TARGET): $(SOURCE) $(VERSION_FAT95_INC)
	$(Q)mkdir -p $(OUTDIR)
	$(Q)echo "  VASM    $@"
	$(Q)$(VASM) $(VASMFLAGS) -o $@ $<
	$(Q)echo "          $$(stat -c%s $@) bytes, md5:$$(md5sum $@ | cut -c1-8)"

# Build tools
$(TARGET_INSTALL95): $(SOURCE_INSTALL95) $(VERSION_INSTALL95_INC)
	$(Q)mkdir -p $(OUTDIR)
	$(Q)echo "  VASM    $@"
	$(Q)$(VASM) $(VASMFLAGS) -o $@ $<
	$(Q)echo "          $$(stat -c%s $@) bytes, md5:$$(md5sum $@ | cut -c1-8)"

$(TARGET_DD): $(SOURCE_DD) $(VERSION_DD_INC)
	$(Q)mkdir -p c
	$(Q)echo "  VASM    $@"
	$(Q)$(VASM) $(VASMFLAGS) -o $@ $<
	$(Q)echo "          $$(stat -c%s $@) bytes, md5:$$(md5sum $@ | cut -c1-8)"

$(TARGET_DEBUG95): $(SOURCE_DEBUG95) $(VERSION_DEBUG95_INC)
	$(Q)mkdir -p c
	$(Q)echo "  VASM    $@"
	$(Q)$(VASM) $(VASMFLAGS) -o $@ $<
	$(Q)echo "          $$(stat -c%s $@) bytes, md5:$$(md5sum $@ | cut -c1-8)"

$(TARGET_SETFILESIZE): $(SOURCE_SETFILESIZE) $(VERSION_SETFILESIZE_INC)
	$(Q)mkdir -p c
	$(Q)echo "  VASM    $@"
	$(Q)$(VASM) $(VASMFLAGS) -o $@ $<
	$(Q)echo "          $$(stat -c%s $@) bytes, md5:$$(md5sum $@ | cut -c1-8)"

$(TARGET_BOOT95): $(SOURCE_BOOT95) $(VERSION_BOOT95_INC)
	$(Q)mkdir -p c
	$(Q)echo "  VASM    $@"
	$(Q)$(VASM) $(VASMFLAGS) -o $@ $<
	$(Q)echo "          $$(stat -c%s $@) bytes, md5:$$(md5sum $@ | cut -c1-8)"

# ============================================================
# Release targets
# ============================================================

# Generate readme.info from template
$(README_NAME).info: $(README_INFO_TEMPLATE)
	@echo "Generating $(README_NAME).info from template..."
	@cp $(README_INFO_TEMPLATE) $(README_NAME).info
	@echo "Generated: $@"

# List of all tools for checksum generation (tool_name:target_file:version:date pairs)
TOOLS = fat95:$(TARGET):$(VERSION):$(DATE) \
	install95:$(TARGET_INSTALL95):$(INSTALL95_VERSION):$(INSTALL95_DATE) \
	dd:$(TARGET_DD):$(DD_VERSION):$(DD_DATE) \
	debug95:$(TARGET_DEBUG95):$(DEBUG95_VERSION):$(DEBUG95_DATE) \
	SetFileSize:$(TARGET_SETFILESIZE):$(SETFILESIZE_VERSION):$(SETFILESIZE_DATE) \
	boot95:$(TARGET_BOOT95):$(BOOT95_VERSION):$(BOOT95_DATE)
TOOLS_TARGETS = $(TARGET) $(TARGET_INSTALL95) $(TARGET_DD) $(TARGET_DEBUG95) $(TARGET_SETFILESIZE) $(TARGET_BOOT95)

# Generate readme from template
$(README_NAME): $(README_TEMPLATE) $(TOOLS_TARGETS) $(README_NAME).info
	@echo "Generating $(README_NAME) from template..."
	@# Generate checksum sections for all tools
	@tool_checksums=""; \
	for tool_info in $(TOOLS); do \
		tool_name=$$(echo $$tool_info | cut -d: -f1); \
		tool_target=$$(echo $$tool_info | cut -d: -f2); \
		tool_version=$$(echo $$tool_info | cut -d: -f3); \
		tool_date=$$(echo $$tool_info | cut -d: -f4); \
		if [ -f "$$tool_target" ]; then \
			tool_size=$$(stat -c%s "$$tool_target" 2>/dev/null || echo 0); \
			tool_md5=$$(md5sum "$$tool_target" 2>/dev/null | cut -d' ' -f1 || echo "N/A"); \
			tool_sha256=$$(sha256sum "$$tool_target" 2>/dev/null | cut -d' ' -f1 || echo "N/A"); \
			tool_checksums="$$tool_checksums$$tool_name $$tool_version ($$tool_date) ($$tool_size bytes):\n  MD5:    $$tool_md5\n  SHA256: $$tool_sha256\n\n"; \
		fi; \
	done; \
	sed -e "s|@VERSION@|$(VERSION)|g" \
		-e "s|@DATE@|$(DATE)|g" \
		-e "s|@TOOL_CHECKSUMS@|$$tool_checksums|" \
		$(README_TEMPLATE) > $@
	@echo "Generated: $@"

# Generate readme only
readme: $(README_NAME) $(README_NAME).info

# Check if lha is installed
check-lha:
	@command -v $(LHA) >/dev/null 2>&1 || { \
		echo "ERROR: lha command not found!"; \
		echo "Install with: sudo dnf install lha"; \
		exit 1; \
	}

# Create Aminet-compatible LHA release
release: all $(README_NAME) $(README_NAME).info check-lha
	@echo "Creating Aminet release: $(ARCHIVE_NAME)"
	@echo "=================================="
	@STAGING=$$(mktemp -d); \
	mkdir -p "$$STAGING/fat95/l" "$$STAGING/fat95/c" "$$STAGING/fat95/src"; \
	echo "Copying files..."; \
	cp $(TARGET) "$$STAGING/fat95/l/"; \
	cp $(TARGET_INSTALL95) "$$STAGING/fat95/l/"; \
	cp $(TARGET_DD) "$$STAGING/fat95/c/"; \
	cp $(TARGET_DEBUG95) "$$STAGING/fat95/c/"; \
	cp $(TARGET_SETFILESIZE) "$$STAGING/fat95/c/"; \
	cp $(TARGET_BOOT95) "$$STAGING/fat95/c/"; \
	cp src/*.s "$$STAGING/fat95/src/"; \
	cp src/*.i "$$STAGING/fat95/src/"; \
	cp $(README_NAME) "$$STAGING/fat95/"; \
	cp LICENSE "$$STAGING/fat95/"; \
	for langdir in english deutsch magyar polska russian espa* fran*; do \
		if [ -d "$$langdir" ] && [ -n "$$(ls -A "$$langdir")" ]; then \
			mkdir -p "$$STAGING/fat95/$$langdir"; \
			cp "$$langdir"/* "$$STAGING/fat95/$$langdir/"; \
		fi; \
	done; \
	cp fat95.info "$$STAGING/"; \
	cp $(README_NAME).info "$$STAGING/fat95/"; \
	for infofile in LICENSE.info english.info deutsch.info magyar.info polska.info russian.info disk.info espa*.info fran*.info; do \
		if [ -f "$$infofile" ]; then cp "$$infofile" "$$STAGING/fat95/"; fi; \
	done; \
	for langdir in english deutsch magyar polska russian espa* fran*; do \
		if [ -d "$$langdir" ]; then \
			find "$$langdir" -name "*.info" -exec cp --parents {} "$$STAGING/fat95/" \; ; \
		fi; \
	done; \
	echo "Creating LHA archive..."; \
	rm -f "$(ARCHIVE_NAME)"; \
	ARCHIVE_PATH="$$STAGING/$(ARCHIVE_NAME)"; \
	CURDIR="$$(pwd)"; \
	(cd "$$STAGING" && LC_ALL=C $(LHA) c "$(ARCHIVE_NAME)" fat95 fat95.info 2>&1 | grep -v "iconv\|multibyte\|Invalid or incomplete"); \
	if [ -f "$$ARCHIVE_PATH" ]; then \
		mv "$$ARCHIVE_PATH" "$$CURDIR/"; \
		echo ""; \
		echo "=================================="; \
		echo "Created: $(ARCHIVE_NAME)"; \
		ls -lh "$(ARCHIVE_NAME)"; \
		echo ""; \
		echo "Contents:"; \
		$(LHA) l "$(ARCHIVE_NAME)"; \
		echo ""; \
		echo "For Aminet upload:"; \
		echo "  1. $(ARCHIVE_NAME)"; \
		echo "  2. $(README_NAME)"; \
		echo ""; \
		echo "Upload to: ftp://main.aminet.net/new"; \
	else \
		echo "ERROR: Failed to create archive"; \
		rm -rf "$$STAGING"; \
		exit 1; \
	fi; \
	rm -rf "$$STAGING"

# ============================================================
# Utility targets
# ============================================================

# Clean build artifacts
clean:
	rm -f $(TARGET) $(TARGET_INSTALL95) $(TARGET_DD) $(TARGET_DEBUG95) $(TARGET_SETFILESIZE) $(TARGET_BOOT95)
	rm -f $(VERSION_FAT95_INC) $(VERSION_INSTALL95_INC) $(VERSION_DD_INC) $(VERSION_DEBUG95_INC) $(VERSION_SETFILESIZE_INC) $(VERSION_BOOT95_INC) $(VERSION_STAMP)

# Clean everything including release files
distclean: clean
	rm -f fat95*.readme fat95*.readme.info fat95*.lha

# Show help
help:
	@echo "Usage: make [V=1] [target]"
	@echo ""
	@echo "Build targets:"
	@echo "  all         - Build fat95 handler + all tools (default)"
	@echo "  fat95       - Build fat95 handler only"
	@echo "  install95   - Build install95 tool only"
	@echo "  dd          - Build dd tool only"
	@echo "  debug95     - Build debug95 tool only"
	@echo "  setfilesize - Build SetFileSize tool only"
	@echo "  boot95      - Build boot95 tool only"
	@echo ""
	@echo "Options:"
	@echo "  V=1                 - Verbose output (show full assembler messages)"
	@echo "  VASM_HOME=/opt/vbcc - vasm installation path"
	@echo ""
	@echo "Release targets:"
	@echo "  readme  - Generate $(README_NAME) from template"
	@echo "  release - Create Aminet LHA archive + readme"
	@echo ""
	@echo "Utility targets:"
	@echo "  clean     - Remove built files"
	@echo "  distclean - Remove all generated files including readme"
	@echo "  help      - Show this help"
	@echo ""
	@echo "Output files:"
	@echo "  $(TARGET) - fat95 filesystem handler (v$(VERSION))"
	@echo "  $(TARGET_INSTALL95) - install95 tool (v$(INSTALL95_VERSION))"
	@echo "  $(TARGET_DD) - dd tool (v$(DD_VERSION))"
	@echo "  $(TARGET_DEBUG95) - debug95 tool (v$(DEBUG95_VERSION))"
	@echo "  $(TARGET_SETFILESIZE) - SetFileSize tool (v$(SETFILESIZE_VERSION))"
	@echo "  $(TARGET_BOOT95) - boot95 tool (v$(BOOT95_VERSION))"
	@echo "  $(README_NAME) - Aminet readme"
	@echo "  $(ARCHIVE_NAME) - Aminet release archive"
	@echo ""
	@echo "Version: $(VERSION) ($(DATE))"

.PHONY: all fat95 install95 dd debug95 setfilesize boot95 clean distclean readme release check-lha help FORCE

# Individual tool targets
fat95: $(TARGET)
install95: $(TARGET_INSTALL95)
dd: $(TARGET_DD)
debug95: $(TARGET_DEBUG95)
setfilesize: $(TARGET_SETFILESIZE)
boot95: $(TARGET_BOOT95)
