; Auto-generated by Makefile.
FILE_VERSION	= 3
FILE_REVISION	= 21
VERSION_STRING	macro
	ifd	__68020__
	dc.b	"$VER: fat95 3.21 (18.04.2026) [68020]"
	else
	dc.b	"$VER: fat95 3.21 (18.04.2026) [68000]"
	endc
	endm
