; Auto-generated by Makefile.
FILE_VERSION	= 3
FILE_REVISION	= 22
VERSION_STRING	macro
	ifd	__68020__
	dc.b	"$VER: fat95 3.22 (16.05.2026) [68020]"
	else
	dc.b	"$VER: fat95 3.22 (16.05.2026) [68000]"
	endc
	endm
